name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: singh465
          password: dockerisfun
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: singh465/myproject:latest
    -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: singh465
          password: dockerisfun
          repository: singh465/myproject
